apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: g9j8a3wn4-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:4b0710c40c4545ec1157f2a5d5e19c6cc13d89d1@sha256:27cf4dc6cfd9592ff8ed79e420a91417ca64c9968b80815fffe34e78c878cd13
          name: container-image
